In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

X=np.array([[78,85,80,82],[65,70,68,72],[90,92,88,91],[72,75,70,74],[85,88,84,86]])
print("Original Dataset:\n",X)

X_std=StandardScaler().fit_transform(X)
print("\nStandardized Data:\n",X_std)

cov_matrix=np.cov(X_std.T)
print("\nCovariance Matrix:\n",cov_matrix)

eigenvalues,eigenvectors=np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n",eigenvalues)
print("\nEigenvectors:\n",eigenvectors)

idx=np.argsort(eigenvalues)[::-1]
eigenvalues=eigenvalues[idx]
eigenvectors=eigenvectors[:,idx]
print("\nSorted Eigenvalues:\n",eigenvalues)
print("\nSorted Eigenvectors:\n",eigenvectors)

k=1
principal_components=eigenvectors[:,:k]
print("\nPrincipal Component Matrix:\n",principal_components)

X_reduced=np.dot(X_std,principal_components)
print("\nReduced Dataset (After PCA):\n",X_reduced)

variance_ratio=eigenvalues/np.sum(eigenvalues)
print("\nVariance Percentage:\n",variance_ratio*100)


Original Dataset:
 [[78 85 80 82]
 [65 70 68 72]
 [90 92 88 91]
 [72 75 70 74]
 [85 88 84 86]]

Standardized Data:
 [[ 0.          0.36487819  0.25649459  0.13975425]
 [-1.45709148 -1.45951277 -1.28247294 -1.25778824]
 [ 1.34500752  1.21626064  1.28247294  1.39754249]
 [-0.67250376 -0.85138245 -1.02597835 -0.97827974]
 [ 0.78458772  0.72975638  0.76948376  0.69877124]]

Covariance Matrix:
 [[1.25       1.22690978 1.22182949 1.22964045]
 [1.22690978 1.25       1.24005798 1.23233754]
 [1.22182949 1.24005798 1.25       1.24565574]
 [1.22964045 1.23233754 1.24565574 1.25      ]]

Eigenvalues:
 [4.94824449e+00 3.21955030e-02 1.25379919e-03 1.83062100e-02]

Eigenvectors:
 [[ 0.49798142  0.84153696 -0.20196409  0.05514122]
 [ 0.50010981 -0.1680098   0.31798467 -0.7877491 ]
 [ 0.50094854 -0.47570306 -0.71075955  0.13258208]
 [ 0.50095434 -0.19311872  0.59406827  0.59902654]]

Sorted Eigenvalues:
 [4.94824449e+00 3.21955030e-02 1.83062100e-02 1.25379919e-03]

Sorted Eigenvectors:
 [[ 0.49798142